/**
 * Maps raw history entry labels (bridge command names or Command class names)
 * to human-readable Chinese labels for the history panel.
 */

const BRIDGE_COMMAND_LABELS: Record<string, string> = {
	"timeline.add_track": "添加轨道",
	"timeline.remove_track": "删除轨道",
	"timeline.add_text": "添加文本",
	"timeline.insert_element": "插入元素",
	"timeline.update_elements": "修改元素",
	"timeline.split_elements": "分割元素",
	"timeline.trim_element": "裁剪元素",
	"timeline.move_elements": "移动元素",
	"timeline.delete_elements": "删除元素",
	"timeline.duplicate_elements": "复制元素",
	"timeline.toggle_muted": "切换静音",
	"timeline.toggle_visibility": "切换可见性",
	"timeline.toggle_track_mute": "切换轨道静音",
	"timeline.toggle_track_visibility": "切换轨道可见性",
	"timeline.toggle_track_linked_style": "切换字幕样式联动",
	"timeline.toggle_source_audio_separation": "切换人声/伴奏分离",
	"timeline.retime_element": "调整播放速度",
	"subtitles.transcribe": "语音转写字幕",
	"subtitles.insert": "插入字幕",
	"media.import": "导入媒体",
	"media.remove": "移除媒体",
	"scenes.create": "新建场景",
	"scenes.switch": "切换场景",
	"scenes.rename": "重命名场景",
	"scenes.delete": "删除场景",
	"scenes.toggle_bookmark": "切换书签",
	"scenes.update_bookmark": "更新书签",
	"scenes.move_bookmark": "移动书签",
	"keyframes.upsert": "添加/更新关键帧",
	"keyframes.remove": "删除关键帧",
	"keyframes.retime": "移动关键帧",
	"keyframes.update_curves": "调整动画曲线",
	"effects.add": "添加特效",
	"effects.remove": "删除特效",
	"effects.update_params": "调整特效参数",
	"effects.toggle": "启用/停用特效",
	"effects.reorder": "调整特效顺序",
	"effects.upsert_keyframe": "特效参数关键帧",
	"effects.remove_keyframe": "删除特效关键帧",
	"masks.add": "添加蒙版",
	"masks.remove": "删除蒙版",
	"masks.toggle_inverted": "反转蒙版",
	"masks.update_params": "调整蒙版参数",
	"masks.freeform_set_path": "编辑蒙版路径",
	"masks.freeform_delete_points": "删除蒙版控制点",
	"project.rename": "重命名项目",
	"project.update_settings": "更新项目设置",
	"selection.set": "设置选中",
	"selection.clear": "清除选中",
	"history.undo": "撤销",
	"history.redo": "重做",
};

const COMMAND_CLASS_LABELS: Record<string, string> = {
	InsertElementCommand: "插入元素",
	DeleteElementsCommand: "删除元素",
	UpdateElementsCommand: "修改元素",
	SplitElementsCommand: "分割元素",
	MoveElementCommand: "移动元素",
	DuplicateElementsCommand: "复制元素",
	PasteCommand: "粘贴",
	PasteKeyframesCommand: "粘贴关键帧",
	AddTrackCommand: "添加轨道",
	RemoveTrackCommand: "删除轨道",
	ToggleTrackMuteCommand: "切换轨道静音",
	ToggleTrackVisibilityCommand: "切换轨道可见性",
	ToggleTrackLinkedStyleCommand: "切换字幕样式联动",
	AddMediaAssetCommand: "导入媒体",
	RemoveMediaAssetCommand: "移除媒体",
	CreateSceneCommand: "新建场景",
	RenameSceneCommand: "重命名场景",
	DeleteSceneCommand: "删除场景",
	ToggleBookmarkCommand: "切换书签",
	UpdateBookmarkCommand: "更新书签",
	MoveBookmarkCommand: "移动书签",
	RemoveBookmarkCommand: "删除书签",
	UpdateProjectSettingsCommand: "更新项目设置",
	UpsertKeyframeCommand: "添加/更新关键帧",
	RemoveKeyframeCommand: "删除关键帧",
	RetimeKeyframeCommand: "移动关键帧",
	UpdateScalarKeyframeCurveCommand: "调整动画曲线",
	AddClipEffectCommand: "添加特效",
	RemoveClipEffectCommand: "删除特效",
	ToggleClipEffectCommand: "启用/停用特效",
	ReorderClipEffectsCommand: "调整特效顺序",
	UpdateClipEffectParamsCommand: "调整特效参数",
	UpsertEffectParamKeyframeCommand: "特效参数关键帧",
	RemoveEffectParamKeyframeCommand: "删除特效关键帧",
	ToggleMaskInvertedCommand: "反转蒙版",
	RemoveMaskCommand: "删除蒙版",
	InsertFreeformPathMaskPointCommand: "添加蒙版控制点",
	DeleteFreeformPathMaskPointsCommand: "删除蒙版控制点",
	ToggleSourceAudioSeparationCommand: "切换人声/伴奏分离",
	RippleShiftElementsCommand: "波纹编辑",
	TracksSnapshotCommand: "时间线变更",
	BatchCommand: "批量操作",
};

export function historyLabel(raw: string): string {
	return BRIDGE_COMMAND_LABELS[raw] ?? COMMAND_CLASS_LABELS[raw] ?? "编辑操作";
}
