/**
 * Maps raw history entry labels (bridge command names or Command class names)
 * to i18n keys for the history panel.
 */
import { t, type MessageKey } from "@/i18n";

const BRIDGE_COMMAND_KEYS: Record<string, MessageKey> = {
	"timeline.add_track": "history.timelineAddTrack",
	"timeline.remove_track": "history.timelineRemoveTrack",
	"timeline.add_text": "history.timelineAddText",
	"timeline.insert_element": "history.timelineInsertElement",
	"timeline.update_elements": "history.timelineUpdateElements",
	"timeline.split_elements": "history.timelineSplitElements",
	"timeline.trim_element": "history.timelineTrimElement",
	"timeline.move_elements": "history.timelineMoveElements",
	"timeline.delete_elements": "history.timelineDeleteElements",
	"timeline.duplicate_elements": "history.timelineDuplicateElements",
	"timeline.toggle_muted": "history.timelineToggleMuted",
	"timeline.toggle_visibility": "history.timelineToggleVisibility",
	"timeline.toggle_track_mute": "history.timelineToggleTrackMute",
	"timeline.toggle_track_visibility": "history.timelineToggleTrackVisibility",
	"timeline.toggle_track_linked_style": "history.timelineToggleTrackLinkedStyle",
	"timeline.toggle_source_audio_separation": "history.timelineToggleSourceAudioSeparation",
	"timeline.retime_element": "history.timelineRetimeElement",
	"subtitles.transcribe": "history.subtitlesTranscribe",
	"subtitles.insert": "history.subtitlesInsert",
	"media.import": "history.mediaImport",
	"media.remove": "history.mediaRemove",
	"scenes.create": "history.scenesCreate",
	"scenes.switch": "history.scenesSwitch",
	"scenes.rename": "history.scenesRename",
	"scenes.delete": "history.scenesDelete",
	"scenes.toggle_bookmark": "history.scenesToggleBookmark",
	"scenes.update_bookmark": "history.scenesUpdateBookmark",
	"scenes.move_bookmark": "history.scenesMoveBookmark",
	"keyframes.upsert": "history.keyframesUpsert",
	"keyframes.remove": "history.keyframesRemove",
	"keyframes.retime": "history.keyframesRetime",
	"keyframes.update_curves": "history.keyframesUpdateCurves",
	"effects.add": "history.effectsAdd",
	"effects.remove": "history.effectsRemove",
	"effects.update_params": "history.effectsUpdateParams",
	"effects.toggle": "history.effectsToggle",
	"effects.reorder": "history.effectsReorder",
	"effects.upsert_keyframe": "history.effectsUpsertKeyframe",
	"effects.remove_keyframe": "history.effectsRemoveKeyframe",
	"masks.add": "history.masksAdd",
	"masks.remove": "history.masksRemove",
	"masks.toggle_inverted": "history.masksToggleInverted",
	"masks.update_params": "history.masksUpdateParams",
	"masks.freeform_set_path": "history.masksFreeformSetPath",
	"masks.freeform_delete_points": "history.masksFreeformDeletePoints",
	"project.rename": "history.projectRename",
	"project.update_settings": "history.projectUpdateSettings",
	"selection.set": "history.selectionSet",
	"selection.clear": "history.selectionClear",
	"history.undo": "history.undo",
	"history.redo": "history.redo",
};

const COMMAND_CLASS_KEYS: Record<string, MessageKey> = {
	InsertElementCommand: "history.timelineInsertElement",
	DeleteElementsCommand: "history.timelineDeleteElements",
	UpdateElementsCommand: "history.timelineUpdateElements",
	SplitElementsCommand: "history.timelineSplitElements",
	MoveElementCommand: "history.timelineMoveElements",
	DuplicateElementsCommand: "history.timelineDuplicateElements",
	PasteCommand: "history.paste",
	PasteKeyframesCommand: "history.pasteKeyframes",
	AddTrackCommand: "history.timelineAddTrack",
	RemoveTrackCommand: "history.timelineRemoveTrack",
	ToggleTrackMuteCommand: "history.timelineToggleTrackMute",
	ToggleTrackVisibilityCommand: "history.timelineToggleTrackVisibility",
	ToggleTrackLinkedStyleCommand: "history.timelineToggleTrackLinkedStyle",
	AddMediaAssetCommand: "history.mediaImport",
	RemoveMediaAssetCommand: "history.mediaRemove",
	CreateSceneCommand: "history.scenesCreate",
	RenameSceneCommand: "history.scenesRename",
	DeleteSceneCommand: "history.scenesDelete",
	ToggleBookmarkCommand: "history.scenesToggleBookmark",
	UpdateBookmarkCommand: "history.scenesUpdateBookmark",
	MoveBookmarkCommand: "history.scenesMoveBookmark",
	RemoveBookmarkCommand: "history.scenesRemoveBookmark",
	UpdateProjectSettingsCommand: "history.projectUpdateSettings",
	UpsertKeyframeCommand: "history.keyframesUpsert",
	RemoveKeyframeCommand: "history.keyframesRemove",
	RetimeKeyframeCommand: "history.keyframesRetime",
	SetKeyframeLoopCommand: "history.keyframesSetLoop",
	UpdateScalarKeyframeCurveCommand: "history.keyframesUpdateCurves",
	AddClipEffectCommand: "history.effectsAdd",
	RemoveClipEffectCommand: "history.effectsRemove",
	ToggleClipEffectCommand: "history.effectsToggle",
	ReorderClipEffectsCommand: "history.effectsReorder",
	UpdateClipEffectParamsCommand: "history.effectsUpdateParams",
	UpsertEffectParamKeyframeCommand: "history.effectsUpsertKeyframe",
	RemoveEffectParamKeyframeCommand: "history.effectsRemoveKeyframe",
	ToggleMaskInvertedCommand: "history.masksToggleInverted",
	RemoveMaskCommand: "history.masksRemove",
	InsertFreeformPathMaskPointCommand: "history.masksInsertFreeformPoint",
	DeleteFreeformPathMaskPointsCommand: "history.masksFreeformDeletePoints",
	ToggleSourceAudioSeparationCommand: "history.timelineToggleSourceAudioSeparation",
	RippleShiftElementsCommand: "history.rippleShiftElements",
	TracksSnapshotCommand: "history.tracksSnapshot",
	BatchCommand: "history.batch",
};

export function historyLabel(raw: string): string {
	const key = BRIDGE_COMMAND_KEYS[raw] ?? COMMAND_CLASS_KEYS[raw];
	return key ? t(key) : t("history.fallback");
}
