export type SoundCategory =
	| "transition"
	| "impact"
	| "ui"
	| "electronic"
	| "foley"
	| "nature"
	| "human";

export interface BuiltinSound {
	id: number;
	name: string;
	file: string;
	duration: number;
	category: SoundCategory;
	author: string;
	license: string;
	source: string;
}

export const SOUND_CATEGORIES: SoundCategory[] = [
	"transition",
	"impact",
	"ui",
	"electronic",
	"foley",
	"nature",
	"human",
];

export const BUILTIN_SOUNDS: BuiltinSound[] = [
	{
		id: 1,
		name: "点击 1",
		file: "ui/click1.mp3",
		duration: 0.09,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/ui-audio",
	},
	{
		id: 2,
		name: "点击 2",
		file: "ui/click2.mp3",
		duration: 0.05,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/ui-audio",
	},
	{
		id: 3,
		name: "点击 3",
		file: "ui/click3.mp3",
		duration: 0.08,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/ui-audio",
	},
	{
		id: 4,
		name: "点击 4",
		file: "ui/click4.mp3",
		duration: 0.04,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/ui-audio",
	},
	{
		id: 5,
		name: "点击 5",
		file: "ui/click5.mp3",
		duration: 0.03,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/ui-audio",
	},
	{
		id: 6,
		name: "鼠标点击",
		file: "ui/mouseclick1.mp3",
		duration: 0.06,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/ui-audio",
	},
	{
		id: 7,
		name: "鼠标释放",
		file: "ui/mouserelease1.mp3",
		duration: 0.07,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/ui-audio",
	},
	{
		id: 8,
		name: "悬停 1",
		file: "ui/rollover1.mp3",
		duration: 0.22,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/ui-audio",
	},
	{
		id: 9,
		name: "悬停 2",
		file: "ui/rollover2.mp3",
		duration: 0.05,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/ui-audio",
	},
	{
		id: 10,
		name: "悬停 3",
		file: "ui/rollover3.mp3",
		duration: 0.07,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/ui-audio",
	},
	{
		id: 11,
		name: "开关 1",
		file: "ui/switch1.mp3",
		duration: 0.31,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/ui-audio",
	},
	{
		id: 12,
		name: "开关 2",
		file: "ui/switch3.mp3",
		duration: 0.36,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/ui-audio",
	},
	{
		id: 13,
		name: "开关 3",
		file: "ui/switch5.mp3",
		duration: 0.31,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/ui-audio",
	},
	{
		id: 14,
		name: "开关 4",
		file: "ui/switch9.mp3",
		duration: 0.26,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/ui-audio",
	},
	{
		id: 15,
		name: "开关 5",
		file: "ui/switch12.mp3",
		duration: 0.05,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/ui-audio",
	},
	{
		id: 16,
		name: "开关 6",
		file: "ui/switch17.mp3",
		duration: 0.33,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/ui-audio",
	},
	{
		id: 17,
		name: "选择 1",
		file: "ui/select-001.mp3",
		duration: 0.04,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 18,
		name: "选择 2",
		file: "ui/select-002.mp3",
		duration: 0.04,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 19,
		name: "选择 3",
		file: "ui/select-003.mp3",
		duration: 0.38,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 20,
		name: "确认 1",
		file: "ui/confirmation-001.mp3",
		duration: 0.29,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 21,
		name: "确认 2",
		file: "ui/confirmation-002.mp3",
		duration: 0.54,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 22,
		name: "确认 3",
		file: "ui/confirmation-003.mp3",
		duration: 0.32,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 23,
		name: "错误提示 1",
		file: "ui/error-001.mp3",
		duration: 0.16,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 24,
		name: "错误提示 2",
		file: "ui/error-002.mp3",
		duration: 0.17,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 25,
		name: "错误提示 3",
		file: "ui/error-003.mp3",
		duration: 0.53,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 26,
		name: "疑问 1",
		file: "ui/question-001.mp3",
		duration: 0.49,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 27,
		name: "疑问 2",
		file: "ui/question-002.mp3",
		duration: 0.33,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 28,
		name: "打开",
		file: "ui/open-001.mp3",
		duration: 0.15,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 29,
		name: "关闭",
		file: "ui/close-001.mp3",
		duration: 0.15,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 30,
		name: "展开",
		file: "ui/maximize-001.mp3",
		duration: 0.26,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 31,
		name: "收起",
		file: "ui/minimize-001.mp3",
		duration: 0.26,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 32,
		name: "滚动 1",
		file: "ui/scroll-001.mp3",
		duration: 1.0,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 33,
		name: "滚动 2",
		file: "ui/scroll-002.mp3",
		duration: 1.0,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 34,
		name: "切换 1",
		file: "ui/toggle-001.mp3",
		duration: 0.14,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 35,
		name: "切换 2",
		file: "ui/toggle-002.mp3",
		duration: 0.14,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 36,
		name: "滴答 1",
		file: "ui/tick-001.mp3",
		duration: 0.04,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 37,
		name: "滴答 2",
		file: "ui/tick-002.mp3",
		duration: 0.02,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 38,
		name: "弹拨 1",
		file: "ui/pluck-001.mp3",
		duration: 0.1,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 39,
		name: "弹拨 2",
		file: "ui/pluck-002.mp3",
		duration: 0.16,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 40,
		name: "钟声提示",
		file: "ui/bong-001.mp3",
		duration: 0.12,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 41,
		name: "返回",
		file: "ui/back-001.mp3",
		duration: 0.06,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 42,
		name: "落下 1",
		file: "ui/drop-001.mp3",
		duration: 0.13,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 43,
		name: "落下 2",
		file: "ui/drop-002.mp3",
		duration: 0.19,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 44,
		name: "玻璃叮咚 1",
		file: "ui/glass-001.mp3",
		duration: 0.28,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 45,
		name: "玻璃叮咚 2",
		file: "ui/glass-002.mp3",
		duration: 0.12,
		category: "ui",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 46,
		name: "轻击 1",
		file: "impact/impactgeneric-light-000.mp3",
		duration: 0.16,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 47,
		name: "轻击 2",
		file: "impact/impactgeneric-light-001.mp3",
		duration: 0.11,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 48,
		name: "轻击 3",
		file: "impact/impactgeneric-light-002.mp3",
		duration: 0.16,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 49,
		name: "拳击 1",
		file: "impact/impactpunch-medium-000.mp3",
		duration: 0.43,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 50,
		name: "拳击 2",
		file: "impact/impactpunch-medium-001.mp3",
		duration: 0.4,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 51,
		name: "重击 1",
		file: "impact/impactpunch-heavy-000.mp3",
		duration: 0.65,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 52,
		name: "重击 2",
		file: "impact/impactpunch-heavy-001.mp3",
		duration: 0.54,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 53,
		name: "金属轻撞 1",
		file: "impact/impactmetal-light-000.mp3",
		duration: 0.37,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 54,
		name: "金属轻撞 2",
		file: "impact/impactmetal-light-001.mp3",
		duration: 0.25,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 55,
		name: "金属撞击 1",
		file: "impact/impactmetal-medium-000.mp3",
		duration: 0.27,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 56,
		name: "金属撞击 2",
		file: "impact/impactmetal-medium-001.mp3",
		duration: 0.14,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 57,
		name: "金属重击 1",
		file: "impact/impactmetal-heavy-000.mp3",
		duration: 0.16,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 58,
		name: "金属重击 2",
		file: "impact/impactmetal-heavy-001.mp3",
		duration: 0.36,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 59,
		name: "木头轻撞 1",
		file: "impact/impactwood-light-000.mp3",
		duration: 0.26,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 60,
		name: "木头轻撞 2",
		file: "impact/impactwood-light-001.mp3",
		duration: 0.26,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 61,
		name: "木头撞击 1",
		file: "impact/impactwood-medium-000.mp3",
		duration: 0.33,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 62,
		name: "木头撞击 2",
		file: "impact/impactwood-medium-001.mp3",
		duration: 0.33,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 63,
		name: "木头重击 1",
		file: "impact/impactwood-heavy-000.mp3",
		duration: 0.31,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 64,
		name: "木头重击 2",
		file: "impact/impactwood-heavy-001.mp3",
		duration: 0.31,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 65,
		name: "玻璃轻碰 1",
		file: "impact/impactglass-light-000.mp3",
		duration: 0.23,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 66,
		name: "玻璃轻碰 2",
		file: "impact/impactglass-light-001.mp3",
		duration: 0.21,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 67,
		name: "玻璃碎裂",
		file: "impact/impactglass-medium-000.mp3",
		duration: 0.54,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 68,
		name: "玻璃砸碎",
		file: "impact/impactglass-heavy-000.mp3",
		duration: 0.24,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 69,
		name: "木板撞击 1",
		file: "impact/impactplank-medium-000.mp3",
		duration: 0.78,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 70,
		name: "木板撞击 2",
		file: "impact/impactplank-medium-001.mp3",
		duration: 0.78,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 71,
		name: "金属盘轻碰",
		file: "impact/impactplate-light-000.mp3",
		duration: 0.54,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 72,
		name: "金属盘撞击",
		file: "impact/impactplate-medium-000.mp3",
		duration: 0.61,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 73,
		name: "金属盘重击",
		file: "impact/impactplate-heavy-000.mp3",
		duration: 0.49,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 74,
		name: "软物撞击 1",
		file: "impact/impactsoft-medium-000.mp3",
		duration: 0.12,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 75,
		name: "软物撞击 2",
		file: "impact/impactsoft-medium-001.mp3",
		duration: 0.18,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 76,
		name: "软物重击",
		file: "impact/impactsoft-heavy-000.mp3",
		duration: 0.53,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 77,
		name: "重锤钟鸣 1",
		file: "impact/impactbell-heavy-000.mp3",
		duration: 1.48,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 78,
		name: "重锤钟鸣 2",
		file: "impact/impactbell-heavy-001.mp3",
		duration: 1.74,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 79,
		name: "凿击 1",
		file: "impact/impactmining-000.mp3",
		duration: 0.94,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 80,
		name: "凿击 2",
		file: "impact/impactmining-001.mp3",
		duration: 0.87,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 81,
		name: "铁皮撞击 1",
		file: "impact/impacttin-medium-000.mp3",
		duration: 0.16,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 82,
		name: "铁皮撞击 2",
		file: "impact/impacttin-medium-001.mp3",
		duration: 0.17,
		category: "impact",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 83,
		name: "激光 1",
		file: "electronic/laser1.mp3",
		duration: 1.1,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 84,
		name: "激光 2",
		file: "electronic/laser3.mp3",
		duration: 0.98,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 85,
		name: "激光 3",
		file: "electronic/laser5.mp3",
		duration: 1.01,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 86,
		name: "激光 4",
		file: "electronic/laser8.mp3",
		duration: 0.99,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 87,
		name: "电击 1",
		file: "electronic/zap1.mp3",
		duration: 1.02,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 88,
		name: "电击 2",
		file: "electronic/zap2.mp3",
		duration: 1.23,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 89,
		name: "电击 3",
		file: "electronic/zaptwotone.mp3",
		duration: 1.31,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 90,
		name: "电击 4",
		file: "electronic/zapthreetoneup.mp3",
		duration: 1.2,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 91,
		name: "能量提升 1",
		file: "electronic/powerup1.mp3",
		duration: 1.2,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 92,
		name: "能量提升 2",
		file: "electronic/powerup3.mp3",
		duration: 1.15,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 93,
		name: "能量提升 3",
		file: "electronic/powerup5.mp3",
		duration: 0.47,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 94,
		name: "能量提升 4",
		file: "electronic/powerup8.mp3",
		duration: 0.6,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 95,
		name: "能量提升 5",
		file: "electronic/powerup11.mp3",
		duration: 0.68,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 96,
		name: "相位跳跃 1",
		file: "electronic/phasejump1.mp3",
		duration: 0.47,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 97,
		name: "相位跳跃 2",
		file: "electronic/phasejump2.mp3",
		duration: 0.39,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 98,
		name: "相位跳跃 3",
		file: "electronic/phasejump3.mp3",
		duration: 0.44,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 99,
		name: "相位上升 1",
		file: "electronic/phaserup1.mp3",
		duration: 0.52,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 100,
		name: "相位上升 2",
		file: "electronic/phaserup2.mp3",
		duration: 0.42,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 101,
		name: "相位下降 1",
		file: "electronic/phaserdown1.mp3",
		duration: 0.47,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 102,
		name: "相位下降 2",
		file: "electronic/phaserdown2.mp3",
		duration: 0.31,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 103,
		name: "电子提示 1",
		file: "electronic/pepsound1.mp3",
		duration: 0.52,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 104,
		name: "电子提示 2",
		file: "electronic/pepsound2.mp3",
		duration: 0.55,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 105,
		name: "电子提示 3",
		file: "electronic/pepsound3.mp3",
		duration: 0.44,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 106,
		name: "电子提示 4",
		file: "electronic/pepsound4.mp3",
		duration: 0.62,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 107,
		name: "音调上升",
		file: "electronic/highup.mp3",
		duration: 0.55,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 108,
		name: "音调下降",
		file: "electronic/highdown.mp3",
		duration: 0.52,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 109,
		name: "低音三连音",
		file: "electronic/lowthreetone.mp3",
		duration: 1.04,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 110,
		name: "三连音",
		file: "electronic/threetone1.mp3",
		duration: 0.85,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 111,
		name: "双连音",
		file: "electronic/twotone1.mp3",
		duration: 0.72,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/digital-audio",
	},
	{
		id: 112,
		name: "故障干扰 1",
		file: "electronic/glitch-001.mp3",
		duration: 0.02,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 113,
		name: "故障干扰 2",
		file: "electronic/glitch-002.mp3",
		duration: 0.03,
		category: "electronic",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 114,
		name: "开门",
		file: "foley/dooropen-1.mp3",
		duration: 0.92,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 115,
		name: "关门 1",
		file: "foley/doorclose-1.mp3",
		duration: 0.68,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 116,
		name: "关门 2",
		file: "foley/doorclose-2.mp3",
		duration: 0.61,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 117,
		name: "吱呀 1",
		file: "foley/creak1.mp3",
		duration: 0.66,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 118,
		name: "吱呀 2",
		file: "foley/creak2.mp3",
		duration: 0.83,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 119,
		name: "翻书 1",
		file: "foley/bookflip1.mp3",
		duration: 0.77,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 120,
		name: "翻书 2",
		file: "foley/bookflip2.mp3",
		duration: 0.43,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 121,
		name: "合书",
		file: "foley/bookclose.mp3",
		duration: 0.23,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 122,
		name: "打开书",
		file: "foley/bookopen.mp3",
		duration: 0.15,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 123,
		name: "布料摩擦 1",
		file: "foley/cloth1.mp3",
		duration: 0.66,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 124,
		name: "布料摩擦 2",
		file: "foley/cloth2.mp3",
		duration: 0.42,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 125,
		name: "布料摩擦 3",
		file: "foley/cloth3.mp3",
		duration: 0.48,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 126,
		name: "劈砍",
		file: "foley/chop.mp3",
		duration: 0.24,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 127,
		name: "拔刀 1",
		file: "foley/drawknife1.mp3",
		duration: 0.4,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 128,
		name: "拔刀 2",
		file: "foley/drawknife2.mp3",
		duration: 0.45,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 129,
		name: "刀割 1",
		file: "foley/knifeslice.mp3",
		duration: 0.6,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 130,
		name: "刀割 2",
		file: "foley/knifeslice2.mp3",
		duration: 0.57,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 131,
		name: "金属咔哒",
		file: "foley/metalclick.mp3",
		duration: 0.45,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 132,
		name: "金属闩",
		file: "foley/metallatch.mp3",
		duration: 0.26,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 133,
		name: "金属锅 1",
		file: "foley/metalpot1.mp3",
		duration: 1.46,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 134,
		name: "金属锅 2",
		file: "foley/metalpot2.mp3",
		duration: 0.94,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 135,
		name: "硬币 1",
		file: "foley/handlecoins.mp3",
		duration: 0.85,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 136,
		name: "硬币 2",
		file: "foley/handlecoins2.mp3",
		duration: 0.34,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 137,
		name: "皮革摩擦",
		file: "foley/handlesmallleather.mp3",
		duration: 0.34,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 138,
		name: "皮革落下",
		file: "foley/dropleather.mp3",
		duration: 0.42,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 139,
		name: "皮带扣",
		file: "foley/belthandle1.mp3",
		duration: 0.28,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 140,
		name: "脚步（硬地） 1",
		file: "foley/footstep00.mp3",
		duration: 0.25,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 141,
		name: "脚步（硬地） 2",
		file: "foley/footstep01.mp3",
		duration: 0.28,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 142,
		name: "脚步（硬地） 3",
		file: "foley/footstep02.mp3",
		duration: 0.24,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 143,
		name: "脚步（硬地） 4",
		file: "foley/footstep03.mp3",
		duration: 0.27,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/rpg-audio",
	},
	{
		id: 144,
		name: "地毯脚步 1",
		file: "foley/footstep-carpet-000.mp3",
		duration: 0.17,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 145,
		name: "地毯脚步 2",
		file: "foley/footstep-carpet-001.mp3",
		duration: 0.14,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 146,
		name: "水泥脚步 1",
		file: "foley/footstep-concrete-000.mp3",
		duration: 0.1,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 147,
		name: "水泥脚步 2",
		file: "foley/footstep-concrete-001.mp3",
		duration: 0.11,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 148,
		name: "草地脚步 1",
		file: "foley/footstep-grass-000.mp3",
		duration: 0.77,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 149,
		name: "草地脚步 2",
		file: "foley/footstep-grass-001.mp3",
		duration: 0.67,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 150,
		name: "雪地脚步 1",
		file: "foley/footstep-snow-000.mp3",
		duration: 0.37,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 151,
		name: "雪地脚步 2",
		file: "foley/footstep-snow-001.mp3",
		duration: 0.37,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 152,
		name: "木地板脚步 1",
		file: "foley/footstep-wood-000.mp3",
		duration: 0.27,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 153,
		name: "木地板脚步 2",
		file: "foley/footstep-wood-001.mp3",
		duration: 0.25,
		category: "foley",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/impact-sounds",
	},
	{
		id: 154,
		name: "搓碟 1",
		file: "transition/scratch-001.mp3",
		duration: 0.14,
		category: "transition",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 155,
		name: "搓碟 2",
		file: "transition/scratch-002.mp3",
		duration: 0.14,
		category: "transition",
		author: "Kenney",
		license: "CC0",
		source: "kenney.nl/interface-sounds",
	},
	{
		id: 156,
		name: "呼啸 01",
		file: "transition/fs-whoosh-transition-01-267951.mp3",
		duration: 2.46,
		category: "transition",
		author: "anagar",
		license: "CC0",
		source: "freesound.org/s/267951",
	},
	{
		id: 157,
		name: "呼啸 02",
		file: "transition/fs-whoosh-transition-02-701104.mp3",
		duration: 2.32,
		category: "transition",
		author: "xkeril",
		license: "CC0",
		source: "freesound.org/s/701104",
	},
	{
		id: 158,
		name: "呼啸 03",
		file: "transition/fs-whoosh-transition-03-802119.mp3",
		duration: 1.0,
		category: "transition",
		author: "ScythicBlade",
		license: "CC0",
		source: "freesound.org/s/802119",
	},
	{
		id: 159,
		name: "呼啸 04",
		file: "transition/fs-whoosh-transition-04-400372.mp3",
		duration: 0.52,
		category: "transition",
		author: "Psykoosiossi",
		license: "CC0",
		source: "freesound.org/s/400372",
	},
	{
		id: 160,
		name: "呼啸 05",
		file: "transition/fs-whoosh-transition-05-612072.mp3",
		duration: 1.44,
		category: "transition",
		author: "BrodieSound",
		license: "CC0",
		source: "freesound.org/s/612072",
	},
	{
		id: 161,
		name: "呼啸 06",
		file: "transition/fs-whoosh-transition-06-398638.mp3",
		duration: 2.73,
		category: "transition",
		author: "DianneLaChauveSouris",
		license: "CC0",
		source: "freesound.org/s/398638",
	},
	{
		id: 162,
		name: "呼啸 07",
		file: "transition/fs-whoosh-transition-07-856169.mp3",
		duration: 3.0,
		category: "transition",
		author: "brktkrgll",
		license: "CC0",
		source: "freesound.org/s/856169",
	},
	{
		id: 163,
		name: "呼啸 08",
		file: "transition/fs-whoosh-transition-08-558827.mp3",
		duration: 3.18,
		category: "transition",
		author: "Kinoton",
		license: "CC0",
		source: "freesound.org/s/558827",
	},
	{
		id: 164,
		name: "呼啸 09",
		file: "transition/fs-whoosh-transition-09-848212.mp3",
		duration: 5.0,
		category: "transition",
		author: "JW_Audio",
		license: "CC0",
		source: "freesound.org/s/848212",
	},
	{
		id: 165,
		name: "呼啸 10",
		file: "transition/fs-whoosh-transition-10-736852.mp3",
		duration: 4.0,
		category: "transition",
		author: "xkeril",
		license: "CC0",
		source: "freesound.org/s/736852",
	},
	{
		id: 166,
		name: "嗖声 01",
		file: "transition/fs-swoosh-01-418005.mp3",
		duration: 3.33,
		category: "transition",
		author: "MasterEngine",
		license: "CC0",
		source: "freesound.org/s/418005",
	},
	{
		id: 167,
		name: "嗖声 02",
		file: "transition/fs-swoosh-02-234555.mp3",
		duration: 4.61,
		category: "transition",
		author: "Electroviolence",
		license: "CC0",
		source: "freesound.org/s/234555",
	},
	{
		id: 168,
		name: "嗖声 03",
		file: "transition/fs-swoosh-03-585257.mp3",
		duration: 0.45,
		category: "transition",
		author: "lesaucisson",
		license: "CC0",
		source: "freesound.org/s/585257",
	},
	{
		id: 169,
		name: "渐强推进 01",
		file: "transition/fs-riser-cinematic-01-859482.mp3",
		duration: 3.0,
		category: "transition",
		author: "BeaconStudio",
		license: "CC0",
		source: "freesound.org/s/859482",
	},
	{
		id: 170,
		name: "渐强推进 02",
		file: "transition/fs-riser-cinematic-02-511861.mp3",
		duration: 3.04,
		category: "transition",
		author: "AudioPapkin",
		license: "CC0",
		source: "freesound.org/s/511861",
	},
	{
		id: 171,
		name: "渐强推进 03",
		file: "transition/fs-riser-cinematic-03-511871.mp3",
		duration: 4.67,
		category: "transition",
		author: "AudioPapkin",
		license: "CC0",
		source: "freesound.org/s/511871",
	},
	{
		id: 172,
		name: "雨声 01",
		file: "nature/fs-rain-01-387064.mp3",
		duration: 8.32,
		category: "nature",
		author: "Smukey9",
		license: "CC0",
		source: "freesound.org/s/387064",
	},
	{
		id: 173,
		name: "雨声 02",
		file: "nature/fs-rain-02-592344.mp3",
		duration: 23.39,
		category: "nature",
		author: "supersnd",
		license: "CC0",
		source: "freesound.org/s/592344",
	},
	{
		id: 174,
		name: "雨声 03",
		file: "nature/fs-rain-03-50061.mp3",
		duration: 27.82,
		category: "nature",
		author: "vibe_crc",
		license: "CC0",
		source: "freesound.org/s/50061",
	},
	{
		id: 175,
		name: "雷声 01",
		file: "nature/fs-thunder-01-193333.mp3",
		duration: 12.46,
		category: "nature",
		author: "soundman9826",
		license: "CC0",
		source: "freesound.org/s/193333",
	},
	{
		id: 176,
		name: "雷声 02",
		file: "nature/fs-thunder-02-683420.mp3",
		duration: 6.42,
		category: "nature",
		author: "SholeColtis",
		license: "CC0",
		source: "freesound.org/s/683420",
	},
	{
		id: 177,
		name: "风声 01",
		file: "nature/fs-wind-01-627878.mp3",
		duration: 26.89,
		category: "nature",
		author: "ideaph",
		license: "CC0",
		source: "freesound.org/s/627878",
	},
	{
		id: 178,
		name: "风声 02",
		file: "nature/fs-wind-02-481145.mp3",
		duration: 11.36,
		category: "nature",
		author: "craigsmith",
		license: "CC0",
		source: "freesound.org/s/481145",
	},
	{
		id: 179,
		name: "森林鸟鸣 01",
		file: "nature/fs-birds-forest-01-344968.mp3",
		duration: 14.24,
		category: "nature",
		author: "VKProduktion",
		license: "CC0",
		source: "freesound.org/s/344968",
	},
	{
		id: 180,
		name: "森林鸟鸣 02",
		file: "nature/fs-birds-forest-02-520538.mp3",
		duration: 3.34,
		category: "nature",
		author: "szegvari",
		license: "CC0",
		source: "freesound.org/s/520538",
	},
	{
		id: 181,
		name: "海浪 01",
		file: "nature/fs-ocean-waves-01-587098.mp3",
		duration: 10.0,
		category: "nature",
		author: "vroooooooooom",
		license: "CC0",
		source: "freesound.org/s/587098",
	},
	{
		id: 182,
		name: "海浪 02",
		file: "nature/fs-ocean-waves-02-792231.mp3",
		duration: 18.9,
		category: "nature",
		author: "YouMightLikeThis",
		license: "CC0",
		source: "freesound.org/s/792231",
	},
	{
		id: 183,
		name: "火焰噼啪 01",
		file: "nature/fs-fire-crackling-01-807942.mp3",
		duration: 8.39,
		category: "nature",
		author: "mbanga",
		license: "CC0",
		source: "freesound.org/s/807942",
	},
	{
		id: 184,
		name: "火焰噼啪 02",
		file: "nature/fs-fire-crackling-02-370938.mp3",
		duration: 24.5,
		category: "nature",
		author: "jmehlferber",
		license: "CC0",
		source: "freesound.org/s/370938",
	},
	{
		id: 185,
		name: "夜晚虫鸣",
		file: "nature/fs-night-crickets-01-177681.mp3",
		duration: 24.62,
		category: "nature",
		author: "kyles",
		license: "CC0",
		source: "freesound.org/s/177681",
	},
	{
		id: 186,
		name: "溪流",
		file: "nature/fs-stream-water-01-786171.mp3",
		duration: 26.0,
		category: "nature",
		author: "sound368",
		license: "CC0",
		source: "freesound.org/s/786171",
	},
	{
		id: 187,
		name: "掌声 01",
		file: "human/fs-applause-01-361557.mp3",
		duration: 6.02,
		category: "human",
		author: "tec_studio",
		license: "CC0",
		source: "freesound.org/s/361557",
	},
	{
		id: 188,
		name: "掌声 02",
		file: "human/fs-applause-02-777709.mp3",
		duration: 8.94,
		category: "human",
		author: "Sadiquecat",
		license: "CC0",
		source: "freesound.org/s/777709",
	},
	{
		id: 189,
		name: "掌声 03",
		file: "human/fs-applause-03-478414.mp3",
		duration: 12.57,
		category: "human",
		author: "thaighaudio",
		license: "CC0",
		source: "freesound.org/s/478414",
	},
	{
		id: 190,
		name: "人群欢呼 01",
		file: "human/fs-crowd-cheering-01-267248.mp3",
		duration: 4.48,
		category: "human",
		author: "BerlinGameScene",
		license: "CC0",
		source: "freesound.org/s/267248",
	},
	{
		id: 191,
		name: "人群欢呼 02",
		file: "human/fs-crowd-cheering-02-221567.mp3",
		duration: 8.39,
		category: "human",
		author: "AlaskaRobotics",
		license: "CC0",
		source: "freesound.org/s/221567",
	},
	{
		id: 192,
		name: "人群欢呼 03",
		file: "human/fs-crowd-cheering-03-511788.mp3",
		duration: 8.35,
		category: "human",
		author: "Kinoton",
		license: "CC0",
		source: "freesound.org/s/511788",
	},
	{
		id: 193,
		name: "笑声 01",
		file: "human/fs-laughter-01-786076.mp3",
		duration: 5.47,
		category: "human",
		author: "amauri8BIT",
		license: "CC0",
		source: "freesound.org/s/786076",
	},
	{
		id: 194,
		name: "笑声 02",
		file: "human/fs-laughter-02-558249.mp3",
		duration: 4.68,
		category: "human",
		author: "Gerent",
		license: "CC0",
		source: "freesound.org/s/558249",
	},
	{
		id: 195,
		name: "倒吸气",
		file: "human/fs-gasp-01-635110.mp3",
		duration: 1.6,
		category: "human",
		author: "RadioCounseling",
		license: "CC0",
		source: "freesound.org/s/635110",
	},
	{
		id: 196,
		name: "人群嘈杂",
		file: "human/fs-crowd-ambience-01-383768.mp3",
		duration: 27.58,
		category: "human",
		author: "deleted_user_7146007",
		license: "CC0",
		source: "freesound.org/s/383768",
	},
];
